name: mmoChatTitle
version: ${releaseVersion}.${buildNumber}
description: Adds a permissions based "Title" filter to mmoChat.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Chat.MMOChatTitle
depend: [mmoCore, mmoChat]
