name: mmoChatTitle
main: mmo.Chat.MMOChatTitle
version: 1.0
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [Spout,mmoCore,mmoChat]

description: Adds a permissions based "Title" to the chat filters
